# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'

  - package-ecosystem: 'dotnet-sdk'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'
    ignore:
      # Ignore patch updates
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '02:00'
    open-pull-requests-limit: 10
    groups:
      microsoft:
        patterns: ['Microsoft*']
        exclude-patterns: ['Microsoft.NET.*']
      system:
        patterns: ['System*']
      xunit:
        patterns: ['Xunit*']
    ignore:
      # Ignore patch updates for some packages
      - dependency-name: 'Microsoft.*'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'System.*'
        update-types: ['version-update:semver-patch']
